version: 2

linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*os.File).Close
        - (io.ReadCloser).Close
        - (*github.com/peng225/orochi/internal/gateway/infra/postgresql.DatastoreRepository).Close
        - (*github.com/peng225/orochi/internal/manager/infra/postgresql.DatastoreRepository).Close
