version: 2

linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*os.File).Close
        - (io.ReadCloser).Close
        - (*database/sql.DB).Close
        - (*database/sql.Tx).Rollback
