// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
)

const deleteBucket = `-- name: DeleteBucket :exec
DELETE FROM bucket
WHERE id = $1
`

func (q *Queries) DeleteBucket(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBucket, id)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM job
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const selectBucket = `-- name: SelectBucket :one
SELECT id, name, ec_config_id, status FROM bucket
WHERE id = $1
`

func (q *Queries) SelectBucket(ctx context.Context, id int64) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, selectBucket, id)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EcConfigID,
		&i.Status,
	)
	return i, err
}

const selectDatastores = `-- name: SelectDatastores :many
SELECT id, base_url, status FROM datastore
`

func (q *Queries) SelectDatastores(ctx context.Context) ([]Datastore, error) {
	rows, err := q.db.QueryContext(ctx, selectDatastores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datastore
	for rows.Next() {
		var i Datastore
		if err := rows.Scan(&i.ID, &i.BaseUrl, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectJobs = `-- name: SelectJobs :many
SELECT id, kind, data FROM job
LIMIT $1
`

func (q *Queries) SelectJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, selectJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(&i.ID, &i.Kind, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDatastoreStatus = `-- name: UpdateDatastoreStatus :exec
UPDATE datastore
SET status = $1
WHERE id = $2
`

type UpdateDatastoreStatusParams struct {
	Status DatastoreStatus
	ID     int64
}

func (q *Queries) UpdateDatastoreStatus(ctx context.Context, arg UpdateDatastoreStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDatastoreStatus, arg.Status, arg.ID)
	return err
}
