// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const insertBucket = `-- name: InsertBucket :one
INSERT INTO bucket (
   name, ec_config_id, status
) VALUES (
  $1, $2, 'active'
)
RETURNING id
`

type InsertBucketParams struct {
	Name       string
	EcConfigID int64
}

func (q *Queries) InsertBucket(ctx context.Context, arg InsertBucketParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBucket, arg.Name, arg.EcConfigID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDatastore = `-- name: InsertDatastore :one
INSERT INTO datastore (
   base_url, status
) VALUES (
  $1, 'active'
)
RETURNING id
`

func (q *Queries) InsertDatastore(ctx context.Context, baseUrl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDatastore, baseUrl)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertECConfig = `-- name: InsertECConfig :one
INSERT INTO ec_config (
   num_data,
   num_parity
) VALUES (
  $1, $2
)
RETURNING id
`

type InsertECConfigParams struct {
	NumData   int32
	NumParity int32
}

func (q *Queries) InsertECConfig(ctx context.Context, arg InsertECConfigParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertECConfig, arg.NumData, arg.NumParity)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO job (
   kind, data
) VALUES (
  $1, $2
)
RETURNING id
`

type InsertJobParams struct {
	Kind string
	Data json.RawMessage
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertJob, arg.Kind, arg.Data)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLocationGroup = `-- name: InsertLocationGroup :one
INSERT INTO location_group (
   current_datastores,
   desired_datastores,
   ec_config_id
) VALUES (
  $1, $2, $3
)
RETURNING id
`

type InsertLocationGroupParams struct {
	CurrentDatastores []int64
	DesiredDatastores []int64
	EcConfigID        int64
}

func (q *Queries) InsertLocationGroup(ctx context.Context, arg InsertLocationGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLocationGroup, pq.Array(arg.CurrentDatastores), pq.Array(arg.DesiredDatastores), arg.EcConfigID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const selectBucket = `-- name: SelectBucket :one
SELECT id, name, ec_config_id, status FROM bucket
WHERE id = $1
`

func (q *Queries) SelectBucket(ctx context.Context, id int64) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, selectBucket, id)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EcConfigID,
		&i.Status,
	)
	return i, err
}

const selectBucketByName = `-- name: SelectBucketByName :one
SELECT id, name, ec_config_id, status FROM bucket
WHERE name = $1
`

func (q *Queries) SelectBucketByName(ctx context.Context, name string) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, selectBucketByName, name)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EcConfigID,
		&i.Status,
	)
	return i, err
}

const selectDatastore = `-- name: SelectDatastore :one
SELECT id, base_url, status FROM datastore
WHERE id = $1
`

func (q *Queries) SelectDatastore(ctx context.Context, id int64) (Datastore, error) {
	row := q.db.QueryRowContext(ctx, selectDatastore, id)
	var i Datastore
	err := row.Scan(&i.ID, &i.BaseUrl, &i.Status)
	return i, err
}

const selectDatastoreIDs = `-- name: SelectDatastoreIDs :many
SELECT id FROM datastore
`

func (q *Queries) SelectDatastoreIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, selectDatastoreIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectECConfigByNumbers = `-- name: SelectECConfigByNumbers :one
SELECT id, num_data, num_parity FROM ec_config
WHERE num_data = $1 AND num_parity = $2
`

type SelectECConfigByNumbersParams struct {
	NumData   int32
	NumParity int32
}

func (q *Queries) SelectECConfigByNumbers(ctx context.Context, arg SelectECConfigByNumbersParams) (EcConfig, error) {
	row := q.db.QueryRowContext(ctx, selectECConfigByNumbers, arg.NumData, arg.NumParity)
	var i EcConfig
	err := row.Scan(&i.ID, &i.NumData, &i.NumParity)
	return i, err
}

const selectECConfigs = `-- name: SelectECConfigs :many
SELECT id, num_data, num_parity from ec_config
`

func (q *Queries) SelectECConfigs(ctx context.Context) ([]EcConfig, error) {
	rows, err := q.db.QueryContext(ctx, selectECConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EcConfig
	for rows.Next() {
		var i EcConfig
		if err := rows.Scan(&i.ID, &i.NumData, &i.NumParity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLocationGroupsByECConfigID = `-- name: SelectLocationGroupsByECConfigID :many
SELECT id, current_datastores, desired_datastores, ec_config_id from location_group
WHERE ec_config_id = $1
`

func (q *Queries) SelectLocationGroupsByECConfigID(ctx context.Context, ecConfigID int64) ([]LocationGroup, error) {
	rows, err := q.db.QueryContext(ctx, selectLocationGroupsByECConfigID, ecConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationGroup
	for rows.Next() {
		var i LocationGroup
		if err := rows.Scan(
			&i.ID,
			pq.Array(&i.CurrentDatastores),
			pq.Array(&i.DesiredDatastores),
			&i.EcConfigID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBucketStatus = `-- name: UpdateBucketStatus :exec
UPDATE bucket
SET status = $1
WHERE id = $2
`

type UpdateBucketStatusParams struct {
	Status BucketStatus
	ID     int64
}

func (q *Queries) UpdateBucketStatus(ctx context.Context, arg UpdateBucketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBucketStatus, arg.Status, arg.ID)
	return err
}

const updateDesiredDatastores = `-- name: UpdateDesiredDatastores :exec
UPDATE location_group
SET desired_datastores = $1
WHERE id = $2
`

type UpdateDesiredDatastoresParams struct {
	DesiredDatastores []int64
	ID                int64
}

func (q *Queries) UpdateDesiredDatastores(ctx context.Context, arg UpdateDesiredDatastoresParams) error {
	_, err := q.db.ExecContext(ctx, updateDesiredDatastores, pq.Array(arg.DesiredDatastores), arg.ID)
	return err
}
