// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type BucketStatus string

const (
	BucketStatusActive  BucketStatus = "active"
	BucketStatusDeleted BucketStatus = "deleted"
)

func (e *BucketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BucketStatus(s)
	case string:
		*e = BucketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BucketStatus: %T", src)
	}
	return nil
}

type NullBucketStatus struct {
	BucketStatus BucketStatus
	Valid        bool // Valid is true if BucketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBucketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BucketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BucketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBucketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BucketStatus), nil
}

type LocationGroupStatus string

const (
	LocationGroupStatusActive   LocationGroupStatus = "active"
	LocationGroupStatusDeleting LocationGroupStatus = "deleting"
)

func (e *LocationGroupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationGroupStatus(s)
	case string:
		*e = LocationGroupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationGroupStatus: %T", src)
	}
	return nil
}

type NullLocationGroupStatus struct {
	LocationGroupStatus LocationGroupStatus
	Valid               bool // Valid is true if LocationGroupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationGroupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LocationGroupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationGroupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationGroupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationGroupStatus), nil
}

type ObjectStatus string

const (
	ObjectStatusCreating ObjectStatus = "creating"
	ObjectStatusUpdating ObjectStatus = "updating"
	ObjectStatusActive   ObjectStatus = "active"
)

func (e *ObjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ObjectStatus(s)
	case string:
		*e = ObjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ObjectStatus: %T", src)
	}
	return nil
}

type NullObjectStatus struct {
	ObjectStatus ObjectStatus
	Valid        bool // Valid is true if ObjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ObjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ObjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ObjectStatus), nil
}

type Bucket struct {
	ID         int64
	Name       string
	EcConfigID int64
	Status     BucketStatus
}

type EcConfig struct {
	ID        int64
	NumData   int32
	NumParity int32
}

type Job struct {
	ID   int64
	Kind string
	Data json.RawMessage
}

type LocationGroup struct {
	ID         int64
	Datastores []int64
	EcConfigID int64
	Status     LocationGroupStatus
}

type ObjectMetadatum struct {
	ID              int64
	Name            string
	Status          ObjectStatus
	BucketID        int64
	LocationGroupID int64
}

type ObjectVersion struct {
	ID         int64
	UpdateTime time.Time
	ObjectID   int64
}
