// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

type Bucket struct {
	ID   int64
	Name string
}

type Datastore struct {
	ID      int64
	BaseUrl string
}

type LocationGroup struct {
	ID                int64
	CurrentDatastores []int64
	DesiredDatastores []int64
}
