// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
)

const selectDatastores = `-- name: SelectDatastores :many
SELECT id, base_url FROM datastore
`

func (q *Queries) SelectDatastores(ctx context.Context) ([]Datastore, error) {
	rows, err := q.db.QueryContext(ctx, selectDatastores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datastore
	for rows.Next() {
		var i Datastore
		if err := rows.Scan(&i.ID, &i.BaseUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
